import type { WebsiteTheme } from "../types";

export const DARK_THEMES: WebsiteTheme[] = [
  {
    id: "theme-dark-default",
    name: "Dark Default",
    nameAr: "داكن افتراضي",
    category: "dark",
    colors: {
      primary: "#3b82f6",
      secondary: "#6366f1",
      accent: "#8b5cf6",
      background: "#0a0a0a",
      surface: "#171717",
      text: "#fafafa",
      textMuted: "#a3a3a3",
      border: "#262626",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-dark-midnight",
    name: "Dark Midnight",
    nameAr: "داكن منتصف الليل",
    category: "dark",
    colors: {
      primary: "#6366f1",
      secondary: "#8b5cf6",
      accent: "#a855f7",
      background: "#020617",
      surface: "#0f172a",
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "#1e293b",
      success: "#10b981",
      warning: "#f59e0b",
      error: "#f43f5e",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-dark-carbon",
    name: "Dark Carbon",
    nameAr: "داكن كربوني",
    category: "dark",
    colors: {
      primary: "#10b981",
      secondary: "#14b8a6",
      accent: "#06b6d4",
      background: "#09090b",
      surface: "#18181b",
      text: "#fafafa",
      textMuted: "#71717a",
      border: "#27272a",
      success: "#22c55e",
      warning: "#eab308",
      error: "#dc2626",
    },
    fonts: { heading: "font-mono", body: "font-sans" },
    borderRadius: "rounded-lg",
  },
  {
    id: "theme-dark-ocean",
    name: "Dark Ocean",
    nameAr: "داكن محيطي",
    category: "dark",
    colors: {
      primary: "#0ea5e9",
      secondary: "#06b6d4",
      accent: "#22d3ee",
      background: "#0c1222",
      surface: "#1a2744",
      text: "#f0f9ff",
      textMuted: "#7dd3fc",
      border: "#1e3a5f",
      success: "#10b981",
      warning: "#f59e0b",
      error: "#f43f5e",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-dark-purple",
    name: "Dark Purple",
    nameAr: "داكن بنفسجي",
    category: "dark",
    colors: {
      primary: "#a855f7",
      secondary: "#c084fc",
      accent: "#e879f9",
      background: "#0d0015",
      surface: "#1a0033",
      text: "#faf5ff",
      textMuted: "#c4b5fd",
      border: "#2e1065",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-dark-rose",
    name: "Dark Rose",
    nameAr: "داكن وردي",
    category: "dark",
    colors: {
      primary: "#f43f5e",
      secondary: "#fb7185",
      accent: "#fda4af",
      background: "#1a0a0e",
      surface: "#2d1219",
      text: "#fff1f2",
      textMuted: "#fecdd3",
      border: "#4c1d2a",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-dark-amber",
    name: "Dark Amber",
    nameAr: "داكن عنبري",
    category: "dark",
    colors: {
      primary: "#f59e0b",
      secondary: "#fbbf24",
      accent: "#fcd34d",
      background: "#1a1206",
      surface: "#292011",
      text: "#fefce8",
      textMuted: "#fde68a",
      border: "#422006",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-lg",
  },
  {
    id: "theme-dark-emerald",
    name: "Dark Emerald",
    nameAr: "داكن زمردي",
    category: "dark",
    colors: {
      primary: "#10b981",
      secondary: "#34d399",
      accent: "#6ee7b7",
      background: "#022c22",
      surface: "#064e3b",
      text: "#ecfdf5",
      textMuted: "#a7f3d0",
      border: "#065f46",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-dark-neon",
    name: "Dark Neon",
    nameAr: "داكن نيون",
    category: "dark",
    colors: {
      primary: "#00ffff",
      secondary: "#ff00ff",
      accent: "#ffff00",
      background: "#000000",
      surface: "#0a0a0a",
      text: "#ffffff",
      textMuted: "#888888",
      border: "#1a1a1a",
      success: "#00ff00",
      warning: "#ffff00",
      error: "#ff0000",
    },
    fonts: { heading: "font-mono", body: "font-sans" },
    borderRadius: "rounded-lg",
  },
  {
    id: "theme-dark-glass",
    name: "Dark Glass",
    nameAr: "داكن زجاجي",
    category: "dark",
    colors: {
      primary: "#818cf8",
      secondary: "#a5b4fc",
      accent: "#c7d2fe",
      background: "#030712",
      surface: "rgba(255,255,255,0.05)",
      text: "#f9fafb",
      textMuted: "#9ca3af",
      border: "rgba(255,255,255,0.1)",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
];

