import type { WebsiteTheme } from "../types";

export const GRADIENT_THEMES: WebsiteTheme[] = [
  {
    id: "theme-gradient-sunset",
    name: "Gradient Sunset",
    nameAr: "تدرج غروب",
    category: "gradient",
    colors: {
      primary: "#f97316",
      secondary: "#ec4899",
      accent: "#8b5cf6",
      background: "#fef3c7",
      surface: "#ffffff",
      text: "#1f2937",
      textMuted: "#6b7280",
      border: "#fcd34d",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-gradient-ocean",
    name: "Gradient Ocean",
    nameAr: "تدرج محيط",
    category: "gradient",
    colors: {
      primary: "#0ea5e9",
      secondary: "#06b6d4",
      accent: "#6366f1",
      background: "#0c4a6e",
      surface: "#075985",
      text: "#f0f9ff",
      textMuted: "#bae6fd",
      border: "#0369a1",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-gradient-aurora",
    name: "Gradient Aurora",
    nameAr: "تدرج شفق",
    category: "gradient",
    colors: {
      primary: "#22c55e",
      secondary: "#06b6d4",
      accent: "#8b5cf6",
      background: "#030712",
      surface: "#111827",
      text: "#f9fafb",
      textMuted: "#9ca3af",
      border: "#1f2937",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-gradient-candy",
    name: "Gradient Candy",
    nameAr: "تدرج حلوى",
    category: "gradient",
    colors: {
      primary: "#ec4899",
      secondary: "#8b5cf6",
      accent: "#06b6d4",
      background: "#fdf4ff",
      surface: "#ffffff",
      text: "#1f2937",
      textMuted: "#6b7280",
      border: "#f5d0fe",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-3xl",
  },
  {
    id: "theme-gradient-midnight",
    name: "Gradient Midnight",
    nameAr: "تدرج منتصف الليل",
    category: "gradient",
    colors: {
      primary: "#6366f1",
      secondary: "#8b5cf6",
      accent: "#ec4899",
      background: "#020617",
      surface: "#0f172a",
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "#1e293b",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-gradient-forest",
    name: "Gradient Forest",
    nameAr: "تدرج غابة",
    category: "gradient",
    colors: {
      primary: "#22c55e",
      secondary: "#10b981",
      accent: "#84cc16",
      background: "#ecfdf5",
      surface: "#ffffff",
      text: "#14532d",
      textMuted: "#166534",
      border: "#a7f3d0",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-gradient-fire",
    name: "Gradient Fire",
    nameAr: "تدرج ناري",
    category: "gradient",
    colors: {
      primary: "#ef4444",
      secondary: "#f97316",
      accent: "#eab308",
      background: "#1c1917",
      surface: "#292524",
      text: "#fef2f2",
      textMuted: "#fca5a5",
      border: "#44403c",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-gradient-royal",
    name: "Gradient Royal",
    nameAr: "تدرج ملكي",
    category: "gradient",
    colors: {
      primary: "#7c3aed",
      secondary: "#4f46e5",
      accent: "#d4af37",
      background: "#0c0a1d",
      surface: "#1a1744",
      text: "#f5f3ff",
      textMuted: "#c4b5fd",
      border: "#312e81",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-gradient-peach",
    name: "Gradient Peach",
    nameAr: "تدرج خوخي",
    category: "gradient",
    colors: {
      primary: "#fb923c",
      secondary: "#f472b6",
      accent: "#c084fc",
      background: "#fefce8",
      surface: "#ffffff",
      text: "#431407",
      textMuted: "#78350f",
      border: "#fed7aa",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-gradient-mesh",
    name: "Gradient Mesh",
    nameAr: "تدرج شبكي",
    category: "gradient",
    colors: {
      primary: "#6366f1",
      secondary: "#ec4899",
      accent: "#f59e0b",
      background: "#030712",
      surface: "#111827",
      text: "#f9fafb",
      textMuted: "#9ca3af",
      border: "#1f2937",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
];

