import type { NavTemplate } from "../types";

export const ECOMMERCE_NAV: NavTemplate[] = [
  {
    id: "nav-ecom-modern",
    name: "E-Commerce Modern",
    nameAr: "تجارة حديث",
    category: "ecommerce",
    styles: {
      nav: "bg-white shadow-sm sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-gray-900",
      links: "hidden lg:flex items-center gap-6",
      link: "text-gray-600 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button:
        "relative p-2 text-gray-600 hover:text-gray-900 transition-colors after:absolute after:-top-1 after:-right-1 after:w-4 after:h-4 after:bg-red-500 after:rounded-full after:text-[10px] after:text-white after:flex after:items-center after:justify-center after:content-['3']",
    },
  },
  {
    id: "nav-ecom-minimal",
    name: "E-Commerce Minimal",
    nameAr: "تجارة بسيط",
    category: "ecommerce",
    styles: {
      nav: "bg-white border-b border-gray-100",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-2xl font-light tracking-widest uppercase text-gray-900",
      links: "hidden lg:flex items-center gap-8",
      link: "text-gray-500 text-xs font-medium tracking-wider uppercase transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button: "p-2 text-gray-600 hover:text-gray-900 transition-colors",
    },
  },
  {
    id: "nav-ecom-dark",
    name: "E-Commerce Dark",
    nameAr: "تجارة داكن",
    category: "ecommerce",
    styles: {
      nav: "bg-gray-950 sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden lg:flex items-center gap-6",
      link: "text-gray-400 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-gray-900 px-4 py-2 rounded-full text-sm font-medium hover:bg-gray-100 transition-colors",
    },
  },
  {
    id: "nav-ecom-colorful",
    name: "E-Commerce Colorful",
    nameAr: "تجارة ملون",
    category: "ecommerce",
    styles: {
      nav: "bg-gradient-to-r from-pink-500 to-orange-500 sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden lg:flex items-center gap-6",
      link: "text-white/80 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-pink-600 px-4 py-2 rounded-full text-sm font-bold hover:bg-white/90 transition-colors",
    },
  },
  {
    id: "nav-ecom-luxury",
    name: "E-Commerce Luxury",
    nameAr: "تجارة فاخر",
    category: "ecommerce",
    styles: {
      nav: "bg-black border-b border-amber-500/30",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-light tracking-[0.3em] uppercase text-amber-500",
      links: "hidden lg:flex items-center gap-10",
      link: "text-gray-400 text-xs font-light tracking-wider uppercase transition-colors duration-200",
      linkHover: "hover:text-amber-500",
      linkActive: "text-amber-500",
      button: "p-2 text-amber-500 hover:text-amber-400 transition-colors",
    },
  },
  {
    id: "nav-ecom-fashion",
    name: "E-Commerce Fashion",
    nameAr: "تجارة أزياء",
    category: "ecommerce",
    styles: {
      nav: "bg-white",
      container: "max-w-7xl mx-auto px-4 h-24 flex flex-col items-center justify-center gap-3",
      logo: "text-3xl font-serif text-gray-900",
      links: "flex items-center gap-8",
      link: "text-gray-500 text-xs font-medium tracking-wider uppercase transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900 border-b border-gray-900",
    },
  },
  {
    id: "nav-ecom-sports",
    name: "E-Commerce Sports",
    nameAr: "تجارة رياضية",
    category: "ecommerce",
    styles: {
      nav: "bg-gray-950",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-black text-white uppercase tracking-wider",
      links: "hidden lg:flex items-center gap-6",
      link: "text-gray-400 text-sm font-bold uppercase tracking-wider transition-colors duration-200",
      linkHover: "hover:text-red-500",
      linkActive: "text-red-500",
      button: "bg-red-600 text-white px-4 py-2 rounded text-sm font-bold uppercase hover:bg-red-500 transition-colors",
    },
  },
  {
    id: "nav-ecom-organic",
    name: "E-Commerce Organic",
    nameAr: "تجارة عضوية",
    category: "ecommerce",
    styles: {
      nav: "bg-amber-50 border-b border-amber-200",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-green-800",
      links: "hidden lg:flex items-center gap-6",
      link: "text-green-700/70 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-green-800",
      linkActive: "text-green-800",
      button: "bg-green-700 text-white px-4 py-2 rounded-full text-sm font-medium hover:bg-green-800 transition-colors",
    },
  },
];

