import type { NavTemplate } from "../types";

export const GLASS_NAV: NavTemplate[] = [
  {
    id: "nav-glass-light",
    name: "Glass Light",
    nameAr: "زجاج فاتح",
    category: "glass",
    styles: {
      nav: "bg-white/70 backdrop-blur-xl border-b border-white/20 sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-gray-900",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-700 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button: "bg-gray-900/90 backdrop-blur text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-900 transition-colors",
    },
  },
  {
    id: "nav-glass-dark",
    name: "Glass Dark",
    nameAr: "زجاج داكن",
    category: "glass",
    styles: {
      nav: "bg-gray-900/70 backdrop-blur-xl border-b border-white/10 sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-300 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white/90 backdrop-blur text-gray-900 px-4 py-2 rounded-lg text-sm font-medium hover:bg-white transition-colors",
    },
  },
  {
    id: "nav-glass-frost",
    name: "Glass Frost",
    nameAr: "زجاج مثلج",
    category: "glass",
    styles: {
      nav: "bg-white/30 backdrop-blur-2xl backdrop-saturate-150 border-b border-white/30 sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-gray-900",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-700 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button:
        "bg-white/50 backdrop-blur text-gray-900 px-4 py-2 rounded-lg text-sm font-medium border border-white/30 hover:bg-white/70 transition-colors",
    },
  },
  {
    id: "nav-glass-colored",
    name: "Glass Colored",
    nameAr: "زجاج ملون",
    category: "glass",
    styles: {
      nav: "bg-gradient-to-r from-purple-500/20 to-pink-500/20 backdrop-blur-xl border-b border-white/20 sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/80 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button:
        "bg-white/20 backdrop-blur text-white px-4 py-2 rounded-lg text-sm font-medium border border-white/30 hover:bg-white/30 transition-colors",
    },
  },
  {
    id: "nav-glass-neon",
    name: "Glass Neon",
    nameAr: "زجاج نيون",
    category: "glass",
    styles: {
      nav: "bg-gray-950/80 backdrop-blur-xl border-b border-cyan-500/30 sticky top-0 z-50 shadow-[0_0_30px_rgba(0,255,255,0.1)]",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-cyan-400",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-400 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-cyan-400",
      linkActive: "text-cyan-400",
      button:
        "bg-cyan-500/20 backdrop-blur text-cyan-400 px-4 py-2 rounded-lg text-sm font-medium border border-cyan-500/50 hover:bg-cyan-500/30 transition-colors",
    },
  },
  {
    id: "nav-glass-aurora",
    name: "Glass Aurora",
    nameAr: "زجاج شفق",
    category: "glass",
    styles: {
      nav: "bg-gradient-to-r from-green-500/10 via-blue-500/10 to-purple-500/10 backdrop-blur-xl border-b border-white/10 sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/70 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button:
        "bg-white/10 backdrop-blur text-white px-4 py-2 rounded-lg text-sm font-medium border border-white/20 hover:bg-white/20 transition-colors",
    },
  },
  {
    id: "nav-glass-floating",
    name: "Glass Floating",
    nameAr: "زجاج عائم",
    category: "glass",
    styles: {
      nav: "fixed top-4 left-1/2 -translate-x-1/2 z-50 bg-white/80 backdrop-blur-xl rounded-2xl shadow-lg border border-white/30",
      container: "px-6 h-14 flex items-center justify-between gap-8",
      logo: "text-lg font-bold text-gray-900",
      links: "hidden md:flex items-center gap-6",
      link: "text-gray-600 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button: "bg-gray-900 text-white px-4 py-1.5 rounded-lg text-sm font-medium hover:bg-gray-800 transition-colors",
    },
  },
  {
    id: "nav-glass-morphism",
    name: "Glassmorphism",
    nameAr: "جلاسمورفيزم",
    category: "glass",
    styles: {
      nav: "bg-white/10 backdrop-blur-2xl backdrop-saturate-200 border-b border-white/20 sticky top-0 z-50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white drop-shadow-lg",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/80 text-sm font-medium transition-all duration-200",
      linkHover: "hover:text-white hover:drop-shadow-lg",
      linkActive: "text-white drop-shadow-lg",
      button:
        "bg-white/20 backdrop-blur text-white px-4 py-2 rounded-xl text-sm font-medium border border-white/30 hover:bg-white/30 transition-all shadow-lg",
    },
  },
];

