import type { NavTemplate } from "../types";

export const GRADIENT_NAV: NavTemplate[] = [
  {
    id: "nav-gradient-sunset",
    name: "Gradient Sunset",
    nameAr: "تدرج غروب",
    category: "gradient",
    styles: {
      nav: "bg-gradient-to-r from-orange-500 via-pink-500 to-purple-600",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/80 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-purple-600 px-4 py-2 rounded-lg text-sm font-medium hover:bg-white/90 transition-colors",
    },
  },
  {
    id: "nav-gradient-ocean",
    name: "Gradient Ocean",
    nameAr: "تدرج محيط",
    category: "gradient",
    styles: {
      nav: "bg-gradient-to-r from-cyan-500 via-blue-500 to-indigo-600",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/80 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-blue-600 px-4 py-2 rounded-lg text-sm font-medium hover:bg-white/90 transition-colors",
    },
  },
  {
    id: "nav-gradient-forest",
    name: "Gradient Forest",
    nameAr: "تدرج غابة",
    category: "gradient",
    styles: {
      nav: "bg-gradient-to-r from-green-600 via-emerald-500 to-teal-500",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/80 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-green-600 px-4 py-2 rounded-lg text-sm font-medium hover:bg-white/90 transition-colors",
    },
  },
  {
    id: "nav-gradient-royal",
    name: "Gradient Royal",
    nameAr: "تدرج ملكي",
    category: "gradient",
    styles: {
      nav: "bg-gradient-to-r from-purple-700 via-violet-600 to-indigo-700",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/80 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-purple-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-white/90 transition-colors",
    },
  },
  {
    id: "nav-gradient-fire",
    name: "Gradient Fire",
    nameAr: "تدرج ناري",
    category: "gradient",
    styles: {
      nav: "bg-gradient-to-r from-red-600 via-orange-500 to-yellow-500",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/90 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-red-600 px-4 py-2 rounded-lg text-sm font-medium hover:bg-white/90 transition-colors",
    },
  },
  {
    id: "nav-gradient-candy",
    name: "Gradient Candy",
    nameAr: "تدرج حلوى",
    category: "gradient",
    styles: {
      nav: "bg-gradient-to-r from-pink-400 via-purple-400 to-indigo-400",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-white/80 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button:
        "bg-white/20 backdrop-blur text-white px-4 py-2 rounded-lg text-sm font-medium border border-white/30 hover:bg-white/30 transition-colors",
    },
  },
  {
    id: "nav-gradient-dark",
    name: "Gradient Dark",
    nameAr: "تدرج داكن",
    category: "gradient",
    styles: {
      nav: "bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-400 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-gradient-to-r from-blue-500 to-purple-500 text-white px-4 py-2 rounded-lg text-sm font-medium hover:opacity-90 transition-opacity",
    },
  },
  {
    id: "nav-gradient-mesh",
    name: "Gradient Mesh",
    nameAr: "تدرج شبكي",
    category: "gradient",
    styles: {
      nav: "bg-[radial-gradient(at_40%_20%,rgba(120,119,198,0.3)_0px,transparent_50%),radial-gradient(at_80%_0%,rgba(255,119,198,0.3)_0px,transparent_50%),radial-gradient(at_0%_50%,rgba(255,198,119,0.3)_0px,transparent_50%)] bg-gray-950",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-300 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button:
        "bg-white/10 backdrop-blur text-white px-4 py-2 rounded-lg text-sm font-medium border border-white/20 hover:bg-white/20 transition-colors",
    },
  },
];

