import type { NavTemplate } from "../types";

export const MINIMAL_NAV: NavTemplate[] = [
  {
    id: "nav-minimal-light",
    name: "Minimal Light",
    nameAr: "بسيط فاتح",
    category: "minimal",
    styles: {
      nav: "bg-white border-b border-gray-100",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-gray-900",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-600 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button: "bg-gray-900 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-800 transition-colors",
    },
  },
  {
    id: "nav-minimal-dark",
    name: "Minimal Dark",
    nameAr: "بسيط داكن",
    category: "minimal",
    styles: {
      nav: "bg-gray-950 border-b border-gray-800",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-400 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-gray-900 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-100 transition-colors",
    },
  },
  {
    id: "nav-minimal-border",
    name: "Minimal Border",
    nameAr: "بسيط بحدود",
    category: "minimal",
    styles: {
      nav: "bg-transparent",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between border-b border-gray-200",
      logo: "text-xl font-bold text-gray-900",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-500 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900 border-b-2 border-gray-900 pb-1",
      button: "border-2 border-gray-900 text-gray-900 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-900 hover:text-white transition-all",
    },
  },
  {
    id: "nav-minimal-centered",
    name: "Minimal Centered",
    nameAr: "بسيط متوسط",
    category: "minimal",
    styles: {
      nav: "bg-white",
      container: "max-w-7xl mx-auto px-4 h-20 flex flex-col items-center justify-center gap-2",
      logo: "text-2xl font-bold text-gray-900",
      links: "flex items-center gap-6",
      link: "text-gray-500 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
    },
  },
  {
    id: "nav-minimal-spaced",
    name: "Minimal Spaced",
    nameAr: "بسيط متباعد",
    category: "minimal",
    styles: {
      nav: "bg-white",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-bold text-gray-900 tracking-widest uppercase",
      links: "hidden md:flex items-center gap-12",
      link: "text-gray-600 text-xs font-medium tracking-widest uppercase transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button: "bg-gray-900 text-white px-6 py-2.5 text-xs font-medium tracking-widest uppercase hover:bg-gray-800 transition-colors",
    },
  },
  {
    id: "nav-minimal-underline",
    name: "Minimal Underline",
    nameAr: "بسيط بخط سفلي",
    category: "minimal",
    styles: {
      nav: "bg-white",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-gray-900",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-600 text-sm font-medium relative after:absolute after:bottom-0 after:left-0 after:w-0 after:h-0.5 after:bg-gray-900 after:transition-all after:duration-300",
      linkHover: "hover:text-gray-900 hover:after:w-full",
      linkActive: "text-gray-900 after:w-full",
    },
  },
  {
    id: "nav-minimal-pill",
    name: "Minimal Pill",
    nameAr: "بسيط حبة",
    category: "minimal",
    styles: {
      nav: "bg-gray-50 py-4",
      container: "max-w-7xl mx-auto px-4 flex items-center justify-between",
      logo: "text-xl font-bold text-gray-900",
      links: "hidden md:flex items-center gap-2 bg-white rounded-full px-2 py-1 shadow-sm",
      link: "text-gray-600 text-sm font-medium px-4 py-2 rounded-full transition-all duration-200",
      linkHover: "hover:text-gray-900 hover:bg-gray-100",
      linkActive: "text-white bg-gray-900",
      button: "bg-gray-900 text-white px-5 py-2.5 rounded-full text-sm font-medium hover:bg-gray-800 transition-colors",
    },
  },
  {
    id: "nav-minimal-dots",
    name: "Minimal Dots",
    nameAr: "بسيط نقاط",
    category: "minimal",
    styles: {
      nav: "bg-white border-b border-gray-100",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-gray-900",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-600 text-sm font-medium relative transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive:
        "text-gray-900 after:absolute after:-bottom-1 after:left-1/2 after:-translate-x-1/2 after:w-1 after:h-1 after:bg-gray-900 after:rounded-full",
    },
  },
];

