import type { WebsiteTheme } from "../types";

export const LIGHT_THEMES: WebsiteTheme[] = [
  {
    id: "theme-light-default",
    name: "Light Default",
    nameAr: "فاتح افتراضي",
    category: "light",
    colors: {
      primary: "#3b82f6",
      secondary: "#6366f1",
      accent: "#8b5cf6",
      background: "#ffffff",
      surface: "#f9fafb",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#e5e7eb",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-light-clean",
    name: "Light Clean",
    nameAr: "فاتح نظيف",
    category: "light",
    colors: {
      primary: "#0f172a",
      secondary: "#334155",
      accent: "#3b82f6",
      background: "#ffffff",
      surface: "#f8fafc",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "#e2e8f0",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-lg",
  },
  {
    id: "theme-light-soft",
    name: "Light Soft",
    nameAr: "فاتح ناعم",
    category: "light",
    colors: {
      primary: "#6366f1",
      secondary: "#8b5cf6",
      accent: "#a855f7",
      background: "#faf5ff",
      surface: "#ffffff",
      text: "#1e1b4b",
      textMuted: "#6b7280",
      border: "#e9d5ff",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-light-warm",
    name: "Light Warm",
    nameAr: "فاتح دافئ",
    category: "light",
    colors: {
      primary: "#ea580c",
      secondary: "#f97316",
      accent: "#fb923c",
      background: "#fffbeb",
      surface: "#ffffff",
      text: "#422006",
      textMuted: "#92400e",
      border: "#fed7aa",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-light-cool",
    name: "Light Cool",
    nameAr: "فاتح بارد",
    category: "light",
    colors: {
      primary: "#0891b2",
      secondary: "#06b6d4",
      accent: "#22d3ee",
      background: "#ecfeff",
      surface: "#ffffff",
      text: "#164e63",
      textMuted: "#0e7490",
      border: "#a5f3fc",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-light-rose",
    name: "Light Rose",
    nameAr: "فاتح وردي",
    category: "light",
    colors: {
      primary: "#e11d48",
      secondary: "#f43f5e",
      accent: "#fb7185",
      background: "#fff1f2",
      surface: "#ffffff",
      text: "#4c0519",
      textMuted: "#be123c",
      border: "#fecdd3",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-light-nature",
    name: "Light Nature",
    nameAr: "فاتح طبيعي",
    category: "light",
    colors: {
      primary: "#16a34a",
      secondary: "#22c55e",
      accent: "#4ade80",
      background: "#f0fdf4",
      surface: "#ffffff",
      text: "#14532d",
      textMuted: "#166534",
      border: "#bbf7d0",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-light-cream",
    name: "Light Cream",
    nameAr: "فاتح كريمي",
    category: "light",
    colors: {
      primary: "#78716c",
      secondary: "#a8a29e",
      accent: "#d6d3d1",
      background: "#fafaf9",
      surface: "#ffffff",
      text: "#1c1917",
      textMuted: "#57534e",
      border: "#e7e5e4",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-lg",
  },
  {
    id: "theme-light-minimal",
    name: "Light Minimal",
    nameAr: "فاتح بسيط",
    category: "light",
    colors: {
      primary: "#000000",
      secondary: "#404040",
      accent: "#737373",
      background: "#ffffff",
      surface: "#fafafa",
      text: "#000000",
      textMuted: "#737373",
      border: "#e5e5e5",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-light-glass",
    name: "Light Glass",
    nameAr: "فاتح زجاجي",
    category: "light",
    colors: {
      primary: "#6366f1",
      secondary: "#8b5cf6",
      accent: "#a855f7",
      background: "#f8fafc",
      surface: "rgba(255,255,255,0.7)",
      text: "#1e293b",
      textMuted: "#64748b",
      border: "rgba(0,0,0,0.1)",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
];

