import type { WebsiteTheme } from "../types";

export const MODERN_THEMES: WebsiteTheme[] = [
  {
    id: "theme-modern-startup",
    name: "Modern Startup",
    nameAr: "حديث شركات ناشئة",
    category: "modern",
    colors: {
      primary: "#6366f1",
      secondary: "#8b5cf6",
      accent: "#f59e0b",
      background: "#ffffff",
      surface: "#f9fafb",
      text: "#111827",
      textMuted: "#6b7280",
      border: "#e5e7eb",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-modern-saas",
    name: "Modern SaaS",
    nameAr: "حديث خدمات سحابية",
    category: "modern",
    colors: {
      primary: "#0ea5e9",
      secondary: "#06b6d4",
      accent: "#8b5cf6",
      background: "#0f172a",
      surface: "#1e293b",
      text: "#f1f5f9",
      textMuted: "#94a3b8",
      border: "#334155",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-modern-agency",
    name: "Modern Agency",
    nameAr: "حديث وكالة",
    category: "modern",
    colors: {
      primary: "#000000",
      secondary: "#171717",
      accent: "#fbbf24",
      background: "#ffffff",
      surface: "#fafafa",
      text: "#171717",
      textMuted: "#525252",
      border: "#e5e5e5",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-modern-fintech",
    name: "Modern Fintech",
    nameAr: "حديث تقنية مالية",
    category: "modern",
    colors: {
      primary: "#10b981",
      secondary: "#059669",
      accent: "#6366f1",
      background: "#f8fafc",
      surface: "#ffffff",
      text: "#0f172a",
      textMuted: "#64748b",
      border: "#e2e8f0",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-2xl",
  },
  {
    id: "theme-modern-ecommerce",
    name: "Modern E-Commerce",
    nameAr: "حديث تجارة إلكترونية",
    category: "modern",
    colors: {
      primary: "#f43f5e",
      secondary: "#ec4899",
      accent: "#fbbf24",
      background: "#ffffff",
      surface: "#fafafa",
      text: "#18181b",
      textMuted: "#71717a",
      border: "#e4e4e7",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-modern-portfolio",
    name: "Modern Portfolio",
    nameAr: "حديث معرض أعمال",
    category: "modern",
    colors: {
      primary: "#171717",
      secondary: "#404040",
      accent: "#3b82f6",
      background: "#fafafa",
      surface: "#ffffff",
      text: "#171717",
      textMuted: "#737373",
      border: "#e5e5e5",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-lg",
  },
  {
    id: "theme-modern-blog",
    name: "Modern Blog",
    nameAr: "حديث مدونة",
    category: "modern",
    colors: {
      primary: "#059669",
      secondary: "#10b981",
      accent: "#f59e0b",
      background: "#ffffff",
      surface: "#f9fafb",
      text: "#1f2937",
      textMuted: "#6b7280",
      border: "#e5e7eb",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-lg",
  },
  {
    id: "theme-modern-dashboard",
    name: "Modern Dashboard",
    nameAr: "حديث لوحة تحكم",
    category: "modern",
    colors: {
      primary: "#6366f1",
      secondary: "#8b5cf6",
      accent: "#22c55e",
      background: "#111827",
      surface: "#1f2937",
      text: "#f9fafb",
      textMuted: "#9ca3af",
      border: "#374151",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
  {
    id: "theme-modern-landing",
    name: "Modern Landing",
    nameAr: "حديث صفحة هبوط",
    category: "modern",
    colors: {
      primary: "#7c3aed",
      secondary: "#a855f7",
      accent: "#f59e0b",
      background: "#faf5ff",
      surface: "#ffffff",
      text: "#1e1b4b",
      textMuted: "#6b7280",
      border: "#e9d5ff",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-3xl",
  },
  {
    id: "theme-modern-minimal",
    name: "Modern Minimal",
    nameAr: "حديث بسيط",
    category: "modern",
    colors: {
      primary: "#18181b",
      secondary: "#3f3f46",
      accent: "#3b82f6",
      background: "#ffffff",
      surface: "#fafafa",
      text: "#18181b",
      textMuted: "#71717a",
      border: "#f4f4f5",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-xl",
  },
];

