import type { WebsiteTheme } from "../types";

export const LUXURY_THEMES: WebsiteTheme[] = [
  {
    id: "theme-luxury-gold",
    name: "Luxury Gold",
    nameAr: "فاخر ذهبي",
    category: "luxury",
    colors: {
      primary: "#d4af37",
      secondary: "#c5a028",
      accent: "#f5d76e",
      background: "#0a0a0a",
      surface: "#141414",
      text: "#fafafa",
      textMuted: "#a3a3a3",
      border: "#2a2a2a",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-black",
    name: "Luxury Black",
    nameAr: "فاخر أسود",
    category: "luxury",
    colors: {
      primary: "#ffffff",
      secondary: "#e5e5e5",
      accent: "#a3a3a3",
      background: "#000000",
      surface: "#0a0a0a",
      text: "#ffffff",
      textMuted: "#737373",
      border: "#262626",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-marble",
    name: "Luxury Marble",
    nameAr: "فاخر رخامي",
    category: "luxury",
    colors: {
      primary: "#1a1a1a",
      secondary: "#333333",
      accent: "#d4af37",
      background: "#f5f5f5",
      surface: "#ffffff",
      text: "#1a1a1a",
      textMuted: "#666666",
      border: "#e0e0e0",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-rose",
    name: "Luxury Rose Gold",
    nameAr: "فاخر وردي ذهبي",
    category: "luxury",
    colors: {
      primary: "#b76e79",
      secondary: "#d4a5a5",
      accent: "#f0d5d5",
      background: "#1a1212",
      surface: "#241a1a",
      text: "#fff5f5",
      textMuted: "#d4a5a5",
      border: "#3d2a2a",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-emerald",
    name: "Luxury Emerald",
    nameAr: "فاخر زمردي",
    category: "luxury",
    colors: {
      primary: "#047857",
      secondary: "#10b981",
      accent: "#d4af37",
      background: "#021a14",
      surface: "#032b22",
      text: "#ecfdf5",
      textMuted: "#a7f3d0",
      border: "#064e3b",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-sapphire",
    name: "Luxury Sapphire",
    nameAr: "فاخر ياقوتي",
    category: "luxury",
    colors: {
      primary: "#1e40af",
      secondary: "#3b82f6",
      accent: "#d4af37",
      background: "#020617",
      surface: "#0f172a",
      text: "#f8fafc",
      textMuted: "#94a3b8",
      border: "#1e3a8a",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-platinum",
    name: "Luxury Platinum",
    nameAr: "فاخر بلاتيني",
    category: "luxury",
    colors: {
      primary: "#e5e5e5",
      secondary: "#d4d4d4",
      accent: "#a3a3a3",
      background: "#0a0a0a",
      surface: "#171717",
      text: "#fafafa",
      textMuted: "#a3a3a3",
      border: "#404040",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-sans", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-velvet",
    name: "Luxury Velvet",
    nameAr: "فاخر مخملي",
    category: "luxury",
    colors: {
      primary: "#7c3aed",
      secondary: "#8b5cf6",
      accent: "#d4af37",
      background: "#0c0615",
      surface: "#1a0f2e",
      text: "#faf5ff",
      textMuted: "#c4b5fd",
      border: "#2e1065",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-champagne",
    name: "Luxury Champagne",
    nameAr: "فاخر شامبانيا",
    category: "luxury",
    colors: {
      primary: "#d4af37",
      secondary: "#f5d76e",
      accent: "#1a1a1a",
      background: "#faf8f5",
      surface: "#ffffff",
      text: "#1a1a1a",
      textMuted: "#666666",
      border: "#e8e4dc",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-none",
  },
  {
    id: "theme-luxury-ruby",
    name: "Luxury Ruby",
    nameAr: "فاخر ياقوت أحمر",
    category: "luxury",
    colors: {
      primary: "#9f1239",
      secondary: "#be123c",
      accent: "#d4af37",
      background: "#1a0a0e",
      surface: "#2d1219",
      text: "#fff1f2",
      textMuted: "#fda4af",
      border: "#4c1d2a",
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
    },
    fonts: { heading: "font-serif", body: "font-sans" },
    borderRadius: "rounded-none",
  },
];

