import type { NavTemplate } from "../types";

export const CORPORATE_NAV: NavTemplate[] = [
  {
    id: "nav-corporate-classic",
    name: "Corporate Classic",
    nameAr: "شركات كلاسيكي",
    category: "corporate",
    styles: {
      nav: "bg-white shadow-sm",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-bold text-blue-900",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-600 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-blue-600",
      linkActive: "text-blue-600",
      button: "bg-blue-600 text-white px-5 py-2.5 rounded text-sm font-medium hover:bg-blue-700 transition-colors",
    },
  },
  {
    id: "nav-corporate-modern",
    name: "Corporate Modern",
    nameAr: "شركات حديث",
    category: "corporate",
    styles: {
      nav: "bg-slate-900",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-slate-400 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-blue-500 text-white px-5 py-2 rounded-lg text-sm font-medium hover:bg-blue-600 transition-colors",
    },
  },
  {
    id: "nav-corporate-minimal",
    name: "Corporate Minimal",
    nameAr: "شركات بسيط",
    category: "corporate",
    styles: {
      nav: "bg-white border-b border-gray-200",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-lg font-semibold text-gray-900",
      links: "hidden md:flex items-center gap-6",
      link: "text-gray-500 text-sm transition-colors duration-200",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button: "text-blue-600 text-sm font-medium hover:text-blue-700 transition-colors",
    },
  },
  {
    id: "nav-corporate-professional",
    name: "Corporate Professional",
    nameAr: "شركات احترافي",
    category: "corporate",
    styles: {
      nav: "bg-gradient-to-r from-slate-800 to-slate-900",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-slate-300 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white border-b-2 border-blue-500 pb-1",
      button:
        "bg-gradient-to-r from-blue-500 to-blue-600 text-white px-5 py-2 rounded text-sm font-medium hover:from-blue-600 hover:to-blue-700 transition-all",
    },
  },
  {
    id: "nav-corporate-finance",
    name: "Corporate Finance",
    nameAr: "شركات مالية",
    category: "corporate",
    styles: {
      nav: "bg-emerald-900",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-emerald-200/70 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-emerald-500 text-white px-5 py-2 rounded text-sm font-medium hover:bg-emerald-400 transition-colors",
    },
  },
  {
    id: "nav-corporate-legal",
    name: "Corporate Legal",
    nameAr: "شركات قانونية",
    category: "corporate",
    styles: {
      nav: "bg-gray-900",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-serif text-amber-500",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-400 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-amber-500",
      linkActive: "text-amber-500",
      button: "border border-amber-500 text-amber-500 px-5 py-2 text-sm font-medium hover:bg-amber-500 hover:text-gray-900 transition-all",
    },
  },
  {
    id: "nav-corporate-tech",
    name: "Corporate Tech",
    nameAr: "شركات تقنية",
    category: "corporate",
    styles: {
      nav: "bg-gray-950 border-b border-gray-800",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-white",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-400 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-cyan-400",
      linkActive: "text-cyan-400",
      button: "bg-cyan-500 text-gray-950 px-5 py-2 rounded-lg text-sm font-bold hover:bg-cyan-400 transition-colors",
    },
  },
  {
    id: "nav-corporate-healthcare",
    name: "Corporate Healthcare",
    nameAr: "شركات طبية",
    category: "corporate",
    styles: {
      nav: "bg-white border-b border-teal-100",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-bold text-teal-700",
      links: "hidden md:flex items-center gap-8",
      link: "text-gray-600 text-sm font-medium transition-colors duration-200",
      linkHover: "hover:text-teal-600",
      linkActive: "text-teal-600",
      button: "bg-teal-600 text-white px-5 py-2 rounded-full text-sm font-medium hover:bg-teal-700 transition-colors",
    },
  },
];

