import type { NavTemplate } from "../types";

export const GAMING_NAV: NavTemplate[] = [
  {
    id: "nav-gaming-cyber",
    name: "Gaming Cyber",
    nameAr: "ألعاب سايبر",
    category: "gaming",
    styles: {
      nav: "bg-gray-950 border-b-2 border-cyan-500 shadow-[0_4px_20px_rgba(0,255,255,0.3)]",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-black text-cyan-400 uppercase tracking-wider",
      links: "hidden md:flex items-center gap-6",
      link: "text-gray-400 text-sm font-bold uppercase tracking-wider transition-all duration-200",
      linkHover: "hover:text-cyan-400",
      linkActive: "text-cyan-400",
      button: "bg-cyan-500 text-gray-950 px-5 py-2 text-sm font-bold uppercase tracking-wider skew-x-[-5deg] hover:bg-cyan-400 transition-colors",
    },
  },
  {
    id: "nav-gaming-neon",
    name: "Gaming Neon",
    nameAr: "ألعاب نيون",
    category: "gaming",
    styles: {
      nav: "bg-black border-b border-purple-500/50",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-black text-purple-500 uppercase tracking-wider drop-shadow-[0_0_10px_rgba(168,85,247,0.8)]",
      links: "hidden md:flex items-center gap-6",
      link: "text-gray-500 text-sm font-bold uppercase tracking-wider transition-all duration-200",
      linkHover: "hover:text-purple-400 hover:drop-shadow-[0_0_10px_rgba(168,85,247,0.5)]",
      linkActive: "text-purple-400 drop-shadow-[0_0_10px_rgba(168,85,247,0.5)]",
      button:
        "bg-purple-600 text-white px-5 py-2 text-sm font-bold uppercase tracking-wider hover:bg-purple-500 transition-colors shadow-[0_0_20px_rgba(168,85,247,0.5)]",
    },
  },
  {
    id: "nav-gaming-rgb",
    name: "Gaming RGB",
    nameAr: "ألعاب RGB",
    category: "gaming",
    styles: {
      nav: "bg-gray-950 border-b-2 border-transparent [background:linear-gradient(#0a0a0a,#0a0a0a)_padding-box,linear-gradient(90deg,#ff0000,#00ff00,#0000ff,#ff0000)_border-box] animate-gradient-x",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-black text-white uppercase tracking-wider",
      links: "hidden md:flex items-center gap-6",
      link: "text-gray-400 text-sm font-bold uppercase tracking-wider transition-all duration-200",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button:
        "bg-gradient-to-r from-red-500 via-green-500 to-blue-500 text-white px-5 py-2 text-sm font-bold uppercase tracking-wider hover:opacity-90 transition-opacity",
    },
  },
  {
    id: "nav-gaming-retro",
    name: "Gaming Retro",
    nameAr: "ألعاب ريترو",
    category: "gaming",
    styles: {
      nav: "bg-gray-900 border-b-4 border-yellow-500",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-mono font-bold text-yellow-400 uppercase",
      links: "hidden md:flex items-center gap-6",
      link: "text-green-400 text-sm font-mono uppercase transition-all duration-200",
      linkHover: "hover:text-yellow-400",
      linkActive: "text-yellow-400",
      button: "bg-yellow-500 text-gray-900 px-5 py-2 text-sm font-mono font-bold uppercase hover:bg-yellow-400 transition-colors",
    },
  },
  {
    id: "nav-gaming-dark",
    name: "Gaming Dark",
    nameAr: "ألعاب داكن",
    category: "gaming",
    styles: {
      nav: "bg-gray-950 border-b border-red-500/30",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-black text-red-500 uppercase tracking-wider",
      links: "hidden md:flex items-center gap-6",
      link: "text-gray-500 text-sm font-bold uppercase tracking-wider transition-all duration-200",
      linkHover: "hover:text-red-500",
      linkActive: "text-red-500",
      button: "bg-red-600 text-white px-5 py-2 text-sm font-bold uppercase tracking-wider hover:bg-red-500 transition-colors",
    },
  },
  {
    id: "nav-gaming-matrix",
    name: "Gaming Matrix",
    nameAr: "ألعاب ماتريكس",
    category: "gaming",
    styles: {
      nav: "bg-black border-b border-green-500/30",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-mono font-bold text-green-500",
      links: "hidden md:flex items-center gap-6",
      link: "text-green-700 text-sm font-mono transition-all duration-200",
      linkHover: "hover:text-green-400",
      linkActive: "text-green-400",
      button: "bg-green-500 text-black px-5 py-2 text-sm font-mono font-bold hover:bg-green-400 transition-colors",
    },
  },
  {
    id: "nav-gaming-fire",
    name: "Gaming Fire",
    nameAr: "ألعاب ناري",
    category: "gaming",
    styles: {
      nav: "bg-gray-950 border-b-2 border-orange-500",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-black bg-gradient-to-r from-red-500 via-orange-500 to-yellow-500 bg-clip-text text-transparent uppercase tracking-wider",
      links: "hidden md:flex items-center gap-6",
      link: "text-gray-400 text-sm font-bold uppercase tracking-wider transition-all duration-200",
      linkHover: "hover:text-orange-400",
      linkActive: "text-orange-400",
      button:
        "bg-gradient-to-r from-red-600 to-orange-500 text-white px-5 py-2 text-sm font-bold uppercase tracking-wider hover:from-red-500 hover:to-orange-400 transition-all",
    },
  },
  {
    id: "nav-gaming-ice",
    name: "Gaming Ice",
    nameAr: "ألعاب جليدي",
    category: "gaming",
    styles: {
      nav: "bg-gray-950 border-b-2 border-cyan-400",
      container: "max-w-7xl mx-auto px-4 h-16 flex items-center justify-between",
      logo: "text-xl font-black bg-gradient-to-r from-cyan-400 via-blue-400 to-cyan-300 bg-clip-text text-transparent uppercase tracking-wider",
      links: "hidden md:flex items-center gap-6",
      link: "text-gray-400 text-sm font-bold uppercase tracking-wider transition-all duration-200",
      linkHover: "hover:text-cyan-400",
      linkActive: "text-cyan-400",
      button:
        "bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-5 py-2 text-sm font-bold uppercase tracking-wider hover:from-cyan-400 hover:to-blue-400 transition-all",
    },
  },
];

