import type { NavTemplate } from "../types";

export const LUXURY_NAV: NavTemplate[] = [
  {
    id: "nav-luxury-gold",
    name: "Luxury Gold",
    nameAr: "فاخر ذهبي",
    category: "luxury",
    styles: {
      nav: "bg-gray-950 border-b border-amber-500/30",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-light tracking-[0.3em] uppercase text-amber-400",
      links: "hidden md:flex items-center gap-10",
      link: "text-amber-200/60 text-xs font-light tracking-[0.2em] uppercase transition-colors duration-300",
      linkHover: "hover:text-amber-400",
      linkActive: "text-amber-400",
      button: "bg-amber-500 text-gray-950 px-6 py-2.5 text-xs font-medium tracking-[0.2em] uppercase hover:bg-amber-400 transition-colors",
    },
  },
  {
    id: "nav-luxury-black",
    name: "Luxury Black",
    nameAr: "فاخر أسود",
    category: "luxury",
    styles: {
      nav: "bg-black border-b border-white/10",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-extralight tracking-[0.4em] uppercase text-white",
      links: "hidden md:flex items-center gap-10",
      link: "text-gray-500 text-xs font-light tracking-[0.2em] uppercase transition-colors duration-300",
      linkHover: "hover:text-white",
      linkActive: "text-white",
      button: "bg-white text-black px-6 py-2.5 text-xs font-medium tracking-[0.2em] uppercase hover:bg-gray-200 transition-colors",
    },
  },
  {
    id: "nav-luxury-white",
    name: "Luxury White",
    nameAr: "فاخر أبيض",
    category: "luxury",
    styles: {
      nav: "bg-white border-b border-gray-200",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-extralight tracking-[0.4em] uppercase text-gray-900",
      links: "hidden md:flex items-center gap-10",
      link: "text-gray-400 text-xs font-light tracking-[0.2em] uppercase transition-colors duration-300",
      linkHover: "hover:text-gray-900",
      linkActive: "text-gray-900",
      button: "bg-gray-900 text-white px-6 py-2.5 text-xs font-medium tracking-[0.2em] uppercase hover:bg-gray-800 transition-colors",
    },
  },
  {
    id: "nav-luxury-rose",
    name: "Luxury Rose",
    nameAr: "فاخر وردي",
    category: "luxury",
    styles: {
      nav: "bg-gradient-to-r from-rose-100 via-pink-50 to-rose-100 border-b border-rose-200",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-light tracking-[0.3em] uppercase text-rose-900",
      links: "hidden md:flex items-center gap-10",
      link: "text-rose-400 text-xs font-light tracking-[0.2em] uppercase transition-colors duration-300",
      linkHover: "hover:text-rose-900",
      linkActive: "text-rose-900",
      button: "bg-rose-600 text-white px-6 py-2.5 text-xs font-medium tracking-[0.2em] uppercase hover:bg-rose-700 transition-colors",
    },
  },
  {
    id: "nav-luxury-emerald",
    name: "Luxury Emerald",
    nameAr: "فاخر زمردي",
    category: "luxury",
    styles: {
      nav: "bg-emerald-950 border-b border-emerald-500/30",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-light tracking-[0.3em] uppercase text-emerald-400",
      links: "hidden md:flex items-center gap-10",
      link: "text-emerald-300/60 text-xs font-light tracking-[0.2em] uppercase transition-colors duration-300",
      linkHover: "hover:text-emerald-400",
      linkActive: "text-emerald-400",
      button: "bg-emerald-500 text-emerald-950 px-6 py-2.5 text-xs font-medium tracking-[0.2em] uppercase hover:bg-emerald-400 transition-colors",
    },
  },
  {
    id: "nav-luxury-sapphire",
    name: "Luxury Sapphire",
    nameAr: "فاخر ياقوتي",
    category: "luxury",
    styles: {
      nav: "bg-blue-950 border-b border-blue-500/30",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-light tracking-[0.3em] uppercase text-blue-400",
      links: "hidden md:flex items-center gap-10",
      link: "text-blue-300/60 text-xs font-light tracking-[0.2em] uppercase transition-colors duration-300",
      linkHover: "hover:text-blue-400",
      linkActive: "text-blue-400",
      button: "bg-blue-500 text-white px-6 py-2.5 text-xs font-medium tracking-[0.2em] uppercase hover:bg-blue-400 transition-colors",
    },
  },
  {
    id: "nav-luxury-velvet",
    name: "Luxury Velvet",
    nameAr: "فاخر مخملي",
    category: "luxury",
    styles: {
      nav: "bg-gradient-to-r from-purple-950 via-purple-900 to-purple-950 border-b border-purple-500/20",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-light tracking-[0.3em] uppercase text-purple-300",
      links: "hidden md:flex items-center gap-10",
      link: "text-purple-400/60 text-xs font-light tracking-[0.2em] uppercase transition-colors duration-300",
      linkHover: "hover:text-purple-300",
      linkActive: "text-purple-300",
      button: "bg-purple-500 text-white px-6 py-2.5 text-xs font-medium tracking-[0.2em] uppercase hover:bg-purple-400 transition-colors",
    },
  },
  {
    id: "nav-luxury-champagne",
    name: "Luxury Champagne",
    nameAr: "فاخر شامبانيا",
    category: "luxury",
    styles: {
      nav: "bg-gradient-to-r from-amber-50 via-yellow-50 to-amber-50 border-b border-amber-200",
      container: "max-w-7xl mx-auto px-4 h-20 flex items-center justify-between",
      logo: "text-xl font-light tracking-[0.3em] uppercase text-amber-800",
      links: "hidden md:flex items-center gap-10",
      link: "text-amber-600/60 text-xs font-light tracking-[0.2em] uppercase transition-colors duration-300",
      linkHover: "hover:text-amber-800",
      linkActive: "text-amber-800",
      button: "bg-amber-700 text-white px-6 py-2.5 text-xs font-medium tracking-[0.2em] uppercase hover:bg-amber-800 transition-colors",
    },
  },
];

